# Generated by Django 5.0.1 on 2024-01-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0003_remove_majorapplication_student_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
