# Generated by Django 5.0.1 on 2024-01-11 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0004_subject_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
    ]
