# Generated by Django 5.0.1 on 2024-01-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0006_application_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
